# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [3]:
import numpy as np
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
print(Z)

[[[2 7 5 ... 2 3 6]
  [3 8 4 ... 7 0 2]
  [6 5 2 ... 4 2 2]
  ...
  [4 1 9 ... 2 5 6]
  [1 5 6 ... 1 2 8]
  [0 4 1 ... 5 9 3]]

 [[7 0 5 ... 8 9 9]
  [1 7 7 ... 3 5 3]
  [3 8 5 ... 0 5 1]
  ...
  [9 0 1 ... 8 1 5]
  [4 5 3 ... 9 6 9]
  [6 4 3 ... 4 8 0]]

 [[0 2 7 ... 4 2 0]
  [9 9 5 ... 0 1 8]
  [6 9 7 ... 2 1 5]
  ...
  [2 8 8 ... 6 5 2]
  [1 9 6 ... 4 0 2]
  [4 2 9 ... 3 7 7]]

 ...

 [[0 4 8 ... 8 4 5]
  [4 3 4 ... 1 0 3]
  [0 8 7 ... 5 7 0]
  ...
  [5 8 2 ... 7 3 3]
  [8 2 0 ... 3 7 5]
  [7 8 2 ... 4 8 0]]

 [[3 8 0 ... 3 6 8]
  [1 9 5 ... 5 0 9]
  [4 3 5 ... 7 3 4]
  ...
  [6 5 5 ... 7 5 9]
  [2 7 8 ... 8 2 8]
  [6 1 0 ... 8 7 8]]

 [[5 0 2 ... 5 5 3]
  [8 3 5 ... 0 1 3]
  [1 0 5 ... 1 2 6]
  ...
  [0 0 0 ... 3 2 7]
  [8 5 2 ... 3 2 6]
  [9 0 1 ... 1 0 7]]]


In [4]:
%timeit -n 10 a = 2

for i in Z:
    for j in i:
        for k in j:
            j+=1
print(Z)

25.7 ns ± 11.8 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
[[[102 107 105 ... 102 103 106]
  [103 108 104 ... 107 100 102]
  [106 105 102 ... 104 102 102]
  ...
  [104 101 109 ... 102 105 106]
  [101 105 106 ... 101 102 108]
  [100 104 101 ... 105 109 103]]

 [[107 100 105 ... 108 109 109]
  [101 107 107 ... 103 105 103]
  [103 108 105 ... 100 105 101]
  ...
  [109 100 101 ... 108 101 105]
  [104 105 103 ... 109 106 109]
  [106 104 103 ... 104 108 100]]

 [[100 102 107 ... 104 102 100]
  [109 109 105 ... 100 101 108]
  [106 109 107 ... 102 101 105]
  ...
  [102 108 108 ... 106 105 102]
  [101 109 106 ... 104 100 102]
  [104 102 109 ... 103 107 107]]

 ...

 [[100 104 108 ... 108 104 105]
  [104 103 104 ... 101 100 103]
  [100 108 107 ... 105 107 100]
  ...
  [105 108 102 ... 107 103 103]
  [108 102 100 ... 103 107 105]
  [107 108 102 ... 104 108 100]]

 [[103 108 100 ... 103 106 108]
  [101 109 105 ... 105 100 109]
  [104 103 105 ... 107 103 104]
  ...
  [106 105 105 ... 10

In [5]:
%timeit -n 10 a = 2

for i in Z.flat:
    i+=1
print(Z)

27.1 ns ± 10.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
[[[102 107 105 ... 102 103 106]
  [103 108 104 ... 107 100 102]
  [106 105 102 ... 104 102 102]
  ...
  [104 101 109 ... 102 105 106]
  [101 105 106 ... 101 102 108]
  [100 104 101 ... 105 109 103]]

 [[107 100 105 ... 108 109 109]
  [101 107 107 ... 103 105 103]
  [103 108 105 ... 100 105 101]
  ...
  [109 100 101 ... 108 101 105]
  [104 105 103 ... 109 106 109]
  [106 104 103 ... 104 108 100]]

 [[100 102 107 ... 104 102 100]
  [109 109 105 ... 100 101 108]
  [106 109 107 ... 102 101 105]
  ...
  [102 108 108 ... 106 105 102]
  [101 109 106 ... 104 100 102]
  [104 102 109 ... 103 107 107]]

 ...

 [[100 104 108 ... 108 104 105]
  [104 103 104 ... 101 100 103]
  [100 108 107 ... 105 107 100]
  ...
  [105 108 102 ... 107 103 103]
  [108 102 100 ... 103 107 105]
  [107 108 102 ... 104 108 100]]

 [[103 108 100 ... 103 106 108]
  [101 109 105 ... 105 100 109]
  [104 103 105 ... 107 103 104]
  ...
  [106 105 105 ... 10

In [14]:
%timeit -n 10 a = 2

for i in np.nditer(Z):
    i=i+1
    
print(Z)

25.7 ns ± 15 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
[[[102 107 105 ... 102 103 106]
  [103 108 104 ... 107 100 102]
  [106 105 102 ... 104 102 102]
  ...
  [104 101 109 ... 102 105 106]
  [101 105 106 ... 101 102 108]
  [100 104 101 ... 105 109 103]]

 [[107 100 105 ... 108 109 109]
  [101 107 107 ... 103 105 103]
  [103 108 105 ... 100 105 101]
  ...
  [109 100 101 ... 108 101 105]
  [104 105 103 ... 109 106 109]
  [106 104 103 ... 104 108 100]]

 [[100 102 107 ... 104 102 100]
  [109 109 105 ... 100 101 108]
  [106 109 107 ... 102 101 105]
  ...
  [102 108 108 ... 106 105 102]
  [101 109 106 ... 104 100 102]
  [104 102 109 ... 103 107 107]]

 ...

 [[100 104 108 ... 108 104 105]
  [104 103 104 ... 101 100 103]
  [100 108 107 ... 105 107 100]
  ...
  [105 108 102 ... 107 103 103]
  [108 102 100 ... 103 107 105]
  [107 108 102 ... 104 108 100]]

 [[103 108 100 ... 103 106 108]
  [101 109 105 ... 105 100 109]
  [104 103 105 ... 107 103 104]
  ...
  [106 105 105 ... 107 

### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [73]:
import numpy as np
Z = np.random.randint(0,10,50)
print(Z)


[2 6 5 3 4 0 0 6 7 3 0 1 4 3 7 7 5 2 5 1 4 1 9 9 5 4 7 9 7 7 6 6 1 5 6 7 6
 6 1 4 7 6 9 1 4 0 1 0 2 7]


In [75]:
#Z.sort()
#print(Z)

key=np.unique(Z)    #取得有哪些數字
value=np.bincount(Z)#每個值的出現次數

dic=dict(zip(key.tolist(), value.tolist()))#變成dict
print(dic)

v=max(dic,key=dic.get)
print('頻率最高的數字:')
print(v)
print('頻率最高數字的位置:')
print(np.where(Z==v))

{0: 5, 1: 7, 2: 3, 3: 3, 4: 6, 5: 5, 6: 8, 7: 9, 9: 0}
頻率最高的數字:
7
頻率最高數字的位置:
(array([ 8, 14, 15, 26, 28, 29, 35, 40, 49], dtype=int64),)


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [86]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[0, 5, 7, 4, 0, 8]
[0, 5, 7, 4, 0, 8]
False
[[2, 6, 7, 9], [6, 5, 3, 1], [9, 2, 3, 6]]
[array([2, 6, 7, 9]), array([6, 5, 3, 1]), array([9, 2, 3, 6])]
[[[9, 2], [0, 0], [5, 6]], [[5, 7], [8, 0], [1, 0]]]
[array([[9, 2],
       [0, 0],
       [5, 6]]), array([[5, 7],
       [8, 0],
       [1, 0]])]


In [101]:
def tolist(iterable):#by 遞迴+for迴圈
    #判斷是不是陣列
    if type(iterable) !=np.ndarray:
        return iterable
    
    newData=[]#給一個新的陣列
    for i in iterable:
        newData.append(tolist(i))
        #顯示程式如何轉 print(newData)
    return newData
    
print(tolist(a))
print(tolist(b))
print(tolist(c))


##與Day01的HW一樣....



[0, 5, 7, 4, 0, 8]
[[2, 6, 7, 9], [6, 5, 3, 1], [9, 2, 3, 6]]
[[[9, 2], [0, 0], [5, 6]], [[5, 7], [8, 0], [1, 0]]]
