# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [16]:
# 記得先 Import 正確的套件

import numpy as np
List1=[]

for i in range(11):
    v=i
    if v>=3 and v<=6:
        v=v*(-1)
    List1.append(v)
    
print(np.array(List1))

[ 0  1  2 -3 -4 -5 -6  7  8  9 10]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [26]:
A = np.random.rand(3, 6)
print(np.array(A))
#print(A[A>0.5])
print(len(A[A>0.5]))


[[0.43308193 0.52713711 0.88205854 0.82936392 0.48284335 0.74190368]
 [0.54643129 0.85620963 0.25132066 0.44196886 0.59199978 0.17027436]
 [0.10227875 0.51806771 0.55409883 0.53375465 0.17522493 0.27635304]]
10
