# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [38]:
'''
Your Code
'''

import numpy as np
a = np.arange(12).reshape(3,4)
print('list(a): ', list(a))#只會把第一層的元素轉換成 List，多層的話只有第一層會轉
print('tolist(): ', a.tolist())#能達成多層的型態轉換


list(a):  [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
tolist():  [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [29]:
# 記得先 Import 正確的套件

import numpy as np


In [30]:

a = np.random.randint(10, size=6) 
print(f'印出的結果:\n {a}')
print(f'陣列的維度:ndim → {a.ndim}')
print(f'陣列的維度大小:shape → {a.shape}')
print(f'陣列中的元素個數:size → {a.size}')
print(f'陣列中的資料型態:dtype → {a.dtype}')
print(f'陣列中的元素占用空間: itemsize → {a.itemsize}')
print(f'陣列的長度: length → {len(a)}')
print(f'陣列的類型: type → {type(a)}')

印出的結果:
 [6 3 3 4 4 1]
陣列的維度:ndim → 1
陣列的維度大小:shape → (6,)
陣列中的元素個數:size → 6
陣列中的資料型態:dtype → int32
陣列中的元素占用空間: itemsize → 4
陣列的長度: length → 6
陣列的類型: type → <class 'numpy.ndarray'>


In [31]:
b = np.random.randint(10, size=(3,4)) 

print(f'印出的結果:\n {b}')
print(f'陣列的維度:ndim → {b.ndim}')
print(f'陣列的維度大小:shape → {b.shape}')
print(f'陣列中的元素個數:size → {b.size}')
print(f'陣列中的資料型態:dtype → {b.dtype}')
print(f'陣列中的元素占用空間: itemsize → {b.itemsize}')
print(f'陣列的長度: length → {len(b)}')
print(f'陣列的類型: type → {type(b)}')

印出的結果:
 [[3 7 6 0]
 [0 2 3 4]
 [9 9 1 7]]
陣列的維度:ndim → 2
陣列的維度大小:shape → (3, 4)
陣列中的元素個數:size → 12
陣列中的資料型態:dtype → int32
陣列中的元素占用空間: itemsize → 4
陣列的長度: length → 3
陣列的類型: type → <class 'numpy.ndarray'>


In [32]:
c = np.random.randint(10, size=(2,3,2)) 

print(f'印出的結果:\n {c}')
print(f'陣列的維度:ndim → {c.ndim}')
print(f'陣列的維度大小:shape → {c.shape}')
print(f'陣列中的元素個數:size → {c.size}')
print(f'陣列中的資料型態:dtype → {c.dtype}')
print(f'陣列中的元素占用空間: itemsize → {c.itemsize}')
print(f'陣列的長度: length → {len(c)}')
print(f'陣列的類型: type → {type(c)}')

印出的結果:
 [[[1 6]
  [4 5]
  [0 2]]

 [[4 8]
  [8 9]
  [6 1]]]
陣列的維度:ndim → 3
陣列的維度大小:shape → (2, 3, 2)
陣列中的元素個數:size → 12
陣列中的資料型態:dtype → int32
陣列中的元素占用空間: itemsize → 4
陣列的長度: length → 2
陣列的類型: type → <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [6]:
import numpy as np
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

[3, 8, 7, 2, 8, 4]
[3, 8, 7, 2, 8, 4]


In [4]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[0, 5, 1, 0], [0, 0, 6, 5], [1, 0, 7, 6]]
[array([0, 5, 1, 0]), array([0, 0, 6, 5]), array([1, 0, 7, 6])]


In [7]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[4, 9], [2, 1], [1, 5]], [[5, 0], [7, 9], [6, 7]]]
[array([[4, 9],
       [2, 1],
       [1, 5]]), array([[5, 0],
       [7, 9],
       [6, 7]])]


In [23]:

def tolist(iterable):#by 遞迴+for迴圈
    #判斷是不是陣列
    if type(iterable) !=np.ndarray:
        return iterable
    
    newData=[]#給一個新的陣列
    for i in iterable:
        newData.append(tolist(i))
        #顯示程式如何轉 print(newData)
    return newData
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

[3, 8, 7, 2, 8, 4]
[[0, 5, 1, 0], [0, 0, 6, 5], [1, 0, 7, 6]]
[[[4, 9], [2, 1], [1, 5]], [[5, 0], [7, 9], [6, 7]]]
