# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [18]:
import numpy as np

a=np.arange(12)
print(a)

print(a.sum())   #numpy的函數，可控制針對某一軸相加
print(np.sum(a)) #numpy的函數
print(sum(a))    #python的內建函數


[ 0  1  2  3  4  5  6  7  8  9 10 11]
66
66
66


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [38]:
# 記得先 Import 正確的套件


import numpy as np
A = np.random.random((5, 5))
print(A)

maxA=A.max()
#print('最大:%10f'%(maxA))
minA=A.min()
#print('最小:%10f'%(minA))
meanA=A.mean()
#print('平均:%10f'%meanA)

newL=[]
for i in A:
    newL.append((i-meanA)/(maxA-minA))
    #資料的正規化(Normalization)是將原始資料的數據按比例縮放於 [0, 1] 區間中，且不改變其原本分佈。-----應該
    
print(np.array(newL))

[[0.54139146 0.96811938 0.47586604 0.3639416  0.16365988]
 [0.26332286 0.69444748 0.94194771 0.3616365  0.1951236 ]
 [0.01898308 0.22168213 0.12545267 0.32554042 0.84976543]
 [0.97325764 0.47299618 0.83216093 0.61362791 0.26770287]
 [0.86433141 0.52341186 0.17329854 0.6077506  0.1016013 ]]
[[ 0.06680539  0.51398059 -0.00185978 -0.11914724 -0.32902575]
 [-0.22458727  0.22719531  0.48655486 -0.1215628  -0.2960544 ]
 [-0.48063494 -0.26822328 -0.36906371 -0.15938847  0.38995554]
 [ 0.51936506 -0.00486716  0.37150749  0.14250314 -0.21999738]
 [ 0.40521947  0.04796427 -0.31892524  0.13634422 -0.39405795]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [60]:
import numpy as np
A=np.random.randint(1,100,10)#0不是正整數，而是自然數
maxA=A.max()
print(A)
print('最大值%d'%(maxA))

index=np.argmax(A)#取出最大值的索引
#print(index)
A[index]=-1#將最大值改為-1
print(A)

[29 20 28  9 66 91 12 86 52 86]
最大值91
[29 20 28  9 66 -1 12 86 52 86]
