# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [52]:
import numpy as np
print(np.zeros((2, 3)))#建立全為0的陣列
print(np.empty((2, 3)))#建立一個沒有任何具體值的陣列
#因NumPy不會初始化陣列內元素的初始值，所以內容將會是不確定的。

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [93]:
# 記得先 Import 正確的套件

import numpy as np

In [103]:
# 參考解答

a = np.random.randn(2, 3)#老師出題是rand，但這結果只會傳0~1，所以我改用randn，這樣元素結果就不會都是0
print(a)

#從陣列轉List
List1=list(a)


List2=List1
for i in range(len(List1)):#取得List的各維度長度
    for j in range(len(List1[0])):#取得List的各維度長度
        #print(List1[i][j])
        List2[i][j]=int(List1[i][j])

        
print(np.array(List2))

[[-0.62809078 -0.30828634 -1.01765248]
 [ 1.15118541  0.21606063  2.35976772]]
[[ 0.  0. -1.]
 [ 1.  0.  2.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [111]:
import  numpy as np
m = 20
n = 40

a=np.random.randint(m,n,size=(3,4))
print(a)

[[35 33 27 24]
 [27 23 24 22]
 [22 38 38 36]]
